<a href="https://colab.research.google.com/github/lethingoctham/bt/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A=[[6,1,4],[1,2,5],[4,3,-1]]
A=np.array(A)
print(A)
B=[[1,2,1],[5,1,6],[7,1,0]]
B=np.array(B)
print("Cộng hai ma trận A và B")
print(A+B)
print("Trừ hai ma trận A và B")
print(A-B)
print("Nhân hai ma trận A và B")
print(A.dot(B))

A_transpose = A.transpose()
B_transpose = B.transpose()



[[ 6  1  4]
 [ 1  2  5]
 [ 4  3 -1]]
Cộng hai ma trận A và B
[[ 7  3  5]
 [ 6  3 11]
 [11  4 -1]]
Trừ hai ma trận A và B
[[ 5 -1  3]
 [-4  1 -1]
 [-3  2 -1]]
Nhân hai ma trận A và B
[[39 17 12]
 [46  9 13]
 [12 10 22]]
A_transpose
